const theme = {
	primary: "#ff4500",
	secondary: "#101010",
	tertiary: "#242424",
	rippleColor: "#FFAB66",
	contentFontColor: "#4d4d4d",
	font: "Khand, Arial Narrow, arial, sans-serif",
	secondaryFont: "roboto, arial, helvetica, clean, sans-serif", //"arial,helvetica,clean,sans-serif",
	thirdFont: "helvetica,verdana,arial,sans-serif",
	lineHeight: "1.8rem",
	fontSize: "1.4rem",
	mobileFontSize: "0.95rem",
	mobileLineHeight: "1.15rem",
	mobileHeaderSize: "3.1rem",
	headerSize: "3.45rem",
	quizButton: "#1486cd",
	quizRipple: "#7AECFF",
	quizCorrect: "rgba(64,136,11,1)",
	quizCorrectOverlay: "#5bc20f",
	// "-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;",
	//"arial, sans-serif",
	contentMaxWidth: "1200px",
};

export { theme };
